import type { Sql } from 'postgres';

const courts = [
  {
    courtId: 1,
    courtName: 'Emerald Turf Court',
    courtImg: '/football_image_1.png',
    courtDescription: 'A lush football field with high-quality turf.',
    ownerName: 'Jason Pritchard',
    ownerInitials: 'JP',
    ownerNumber: '312-555-8927',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 7,
    sportCategory: 'football',
  },
  {
    courtId: 2,
    courtName: 'Summit Arena',
    courtImg: '/football_image_2.png',
    courtDescription: 'Large stadium perfect for amateur matches.',
    ownerName: 'Mary Smith',
    ownerInitials: 'MS',
    ownerNumber: '312-555-1234',
    workingHours: '8:00 to 21:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 15,
    sportCategory: 'football',
  },
  {
    courtId: 3,
    courtName: 'Riverfront Field',
    courtImg: '/football_image_3.png',
    courtDescription: 'Scenic riverside football field.',
    ownerName: 'Robert King',
    ownerInitials: 'RK',
    ownerNumber: '312-555-5678',
    workingHours: '6:00 to 23:00',
    weekendHours: '6:00 to 23:00',
    pricePerHour: 10,
    sportCategory: 'football',
  },
  {
    courtId: 4,
    courtName: 'Greenfield Grounds',
    courtImg: '/football_image_4.png',
    courtDescription: 'Modern facility with locker rooms and lights.',
    ownerName: 'Linda Torres',
    ownerInitials: 'LT',
    ownerNumber: '312-555-9876',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 12,
    sportCategory: 'football',
  },
  {
    courtId: 5,
    courtName: 'Iron Gate Field',
    courtImg: '/football_image_5.png',
    courtDescription: 'Artificial turf with premium seating.',
    ownerName: 'Tom Edison',
    ownerInitials: 'TE',
    ownerNumber: '312-555-8765',
    workingHours: '9:00 to 20:00',
    weekendHours: '9:00 to 18:00',
    pricePerHour: 20,
    sportCategory: 'football',
  },
  {
    courtId: 6,
    courtName: 'City Kickoff Center',
    courtImg: '/football_image_6.png',
    courtDescription: 'Compact field ideal for quick matches.',
    ownerName: 'Sally Brown',
    ownerInitials: 'SB',
    ownerNumber: '312-555-5432',
    workingHours: '8:00 to 21:00',
    weekendHours: '8:00 to 19:00',
    pricePerHour: 8,
    sportCategory: 'football',
  },
  {
    courtId: 7,
    courtName: 'Hoops Heaven',
    courtImg: '/basketball_image_1.png',
    courtDescription: 'Spacious court with state-of-the-art flooring.',
    ownerName: 'Michael Green',
    ownerInitials: 'MG',
    ownerNumber: '312-555-2345',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 5,
    sportCategory: 'basketball',
  },
  {
    courtId: 8,
    courtName: "Baller's Dome",
    courtImg: '/basketball_image_2.png',
    courtDescription: 'Indoor court with a vibrant atmosphere.',
    ownerName: 'Diana Young',
    ownerInitials: 'DY',
    ownerNumber: '312-555-6543',
    workingHours: '7:00 to 23:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 10,
    sportCategory: 'basketball',
  },
  {
    courtId: 9,
    courtName: 'Rim Rock Arena',
    courtImg: '/basketball_image_3.png',
    courtDescription: 'Outdoor basketball court near downtown.',
    ownerName: 'Kevin Lewis',
    ownerInitials: 'KL',
    ownerNumber: '312-555-3210',
    workingHours: '6:00 to 20:00',
    weekendHours: '6:00 to 18:00',
    pricePerHour: 6,
    sportCategory: 'basketball',
  },
  {
    courtId: 10,
    courtName: 'The Hardwood Palace',
    courtImg: '/basketball_image_4.png',
    courtDescription: 'Professional-grade court with top-notch lighting.',
    ownerName: 'Rachel Kim',
    ownerInitials: 'RK',
    ownerNumber: '312-555-6789',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 22:00',
    pricePerHour: 12,
    sportCategory: 'basketball',
  },
  {
    courtId: 11,
    courtName: 'Elite Sports Center',
    courtImg: '/basketball_image_5.png',
    courtDescription: 'Multipurpose court for all basketball levels.',
    ownerName: 'Frank Johnson',
    ownerInitials: 'FJ',
    ownerNumber: '312-555-2341',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 15,
    sportCategory: 'basketball',
  },
  {
    courtId: 12,
    courtName: 'Hoop Dreams Facility',
    courtImg: '/basketball_image_6.png',
    courtDescription: 'Training-focused facility with multiple courts.',
    ownerName: 'Emily Davis',
    ownerInitials: 'ED',
    ownerNumber: '312-555-7890',
    workingHours: '9:00 to 21:00',
    weekendHours: '9:00 to 18:00',
    pricePerHour: 7,
    sportCategory: 'basketball',
  },
  {
    courtId: 13,
    courtName: 'Sand Spike Court',
    courtImg: '/volleyball_image_1.png',
    courtDescription: 'Beach-style volleyball court with soft sand.',
    ownerName: 'Alice Carter',
    ownerInitials: 'AC',
    ownerNumber: '312-555-3456',
    workingHours: '7:00 to 20:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 10,
    sportCategory: 'volleyball',
  },
  {
    courtId: 14,
    courtName: 'Ace Point Arena',
    courtImg: '/volleyball_image_2.png',
    courtDescription: 'Indoor court with full facilities and seating.',
    ownerName: 'Brian Wilson',
    ownerInitials: 'BW',
    ownerNumber: '312-555-6541',
    workingHours: '6:00 to 21:00',
    weekendHours: '6:00 to 21:00',
    pricePerHour: 15,
    sportCategory: 'volleyball',
  },
  {
    courtId: 15,
    courtName: 'Net Champs Hub',
    courtImg: '/volleyball_image_3.png',
    courtDescription: 'Modern venue perfect for tournaments.',
    ownerName: 'Carol James',
    ownerInitials: 'CJ',
    ownerNumber: '312-555-9987',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 12,
    sportCategory: 'volleyball',
  },
  {
    courtId: 16,
    courtName: 'Volley Masters Dome',
    courtImg: '/volleyball_image_4.png',
    courtDescription: 'Spacious facility with adjustable net heights.',
    ownerName: 'David Miller',
    ownerInitials: 'DM',
    ownerNumber: '312-555-8876',
    workingHours: '7:00 to 23:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 20,
    sportCategory: 'volleyball',
  },
  {
    courtId: 17,
    courtName: 'Beach Bash Court',
    courtImg: '/volleyball_image_5.png',
    courtDescription: 'Outdoor court with ocean views and shaded areas.',
    ownerName: 'Ellen Stone',
    ownerInitials: 'ES',
    ownerNumber: '312-555-2321',
    workingHours: '9:00 to 19:00',
    weekendHours: '9:00 to 19:00',
    pricePerHour: 8,
    sportCategory: 'volleyball',
  },
  {
    courtId: 18,
    courtName: "The Spikers' Arena",
    courtImg: '/volleyball_image_6.png',
    courtDescription: 'Advanced court for both pros and beginners.',
    ownerName: 'Frank Porter',
    ownerInitials: 'FP',
    ownerNumber: '312-555-6674',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 14,
    sportCategory: 'volleyball',
  },
  {
    courtId: 19,
    courtName: 'Topspin Tennis Court',
    courtImg: '/tennis_image_1.png',
    courtDescription: 'Full-size tennis court with excellent facilities.',
    ownerName: 'George Lee',
    ownerInitials: 'GL',
    ownerNumber: '312-555-4678',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 12,
    sportCategory: 'tennis',
  },
  {
    courtId: 20,
    courtName: 'Grand Slam Ground',
    courtImg: '/tennis_image_2.png',
    courtDescription: 'Premium tennis court ideal for training.',
    ownerName: 'Hannah Black',
    ownerInitials: 'HB',
    ownerNumber: '312-555-0987',
    workingHours: '8:00 to 21:00',
    weekendHours: '8:00 to 21:00',
    pricePerHour: 18,
    sportCategory: 'tennis',
  },
  {
    courtId: 21,
    courtName: 'Court of Aces',
    courtImg: '/tennis_image_3.png',
    courtDescription: 'Scenic tennis court surrounded by nature.',
    ownerName: 'Ian Turner',
    ownerInitials: 'IT',
    ownerNumber: '312-555-5431',
    workingHours: '6:00 to 20:00',
    weekendHours: '6:00 to 20:00',
    pricePerHour: 15,
    sportCategory: 'tennis',
  },
  {
    courtId: 22,
    courtName: 'Tennis Master Arena',
    courtImg: '/tennis_image_4.png',
    courtDescription: 'Professional-grade court for top matches.',
    ownerName: 'Jenna Cole',
    ownerInitials: 'JC',
    ownerNumber: '312-555-8765',
    workingHours: '7:00 to 23:00',
    weekendHours: '7:00 to 23:00',
    pricePerHour: 20,
    sportCategory: 'tennis',
  },
  {
    courtId: 23,
    courtName: 'Rally Point Court',
    courtImg: '/tennis_image_5.png',
    courtDescription: 'Modern court with audience seating available.',
    ownerName: 'Kevin Ross',
    ownerInitials: 'KR',
    ownerNumber: '312-555-3214',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 18:00',
    pricePerHour: 9,
    sportCategory: 'tennis',
  },
  {
    courtId: 24,
    courtName: 'Smash Zone Facility',
    courtImg: '/tennis_image_6.png',
    courtDescription: 'High-quality surface for all playing styles.',
    ownerName: 'Laura Miles',
    ownerInitials: 'LM',
    ownerNumber: '312-555-8763',
    workingHours: '9:00 to 21:00',
    weekendHours: '9:00 to 21:00',
    pricePerHour: 11,
    sportCategory: 'tennis',
  },
  {
    courtId: 25,
    courtName: 'Iron Gloves Gym',
    courtImg: '/boxing_image_1.png',
    courtDescription: 'Boxing gym with top-notch equipment and trainers.',
    ownerName: 'Mike Boxer',
    ownerInitials: 'MB',
    ownerNumber: '312-555-4321',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 22:00',
    pricePerHour: 17,
    sportCategory: 'boxing',
  },
  {
    courtId: 26,
    courtName: 'The Ring Center',
    courtImg: '/boxing_image_2.png',
    courtDescription: 'Spacious facility for all levels of boxing.',
    ownerName: 'Nancy Powers',
    ownerInitials: 'NP',
    ownerNumber: '312-555-6548',
    workingHours: '6:00 to 20:00',
    weekendHours: '6:00 to 20:00',
    pricePerHour: 22,
    sportCategory: 'boxing',
  },
  {
    courtId: 27,
    courtName: 'Knockout Arena',
    courtImg: '/boxing_image_3.png',
    courtDescription: 'Popular training spot for amateur boxers.',
    ownerName: 'Oliver Smith',
    ownerInitials: 'OS',
    ownerNumber: '312-555-9098',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 14,
    sportCategory: 'boxing',
  },
  {
    courtId: 28,
    courtName: 'Punch Palace',
    courtImg: '/boxing_image_4.png',
    courtDescription: 'Modern gym with certified trainers.',
    ownerName: 'Peter Jones',
    ownerInitials: 'PJ',
    ownerNumber: '312-555-7685',
    workingHours: '7:00 to 21:00',
    weekendHours: '7:00 to 19:00',
    pricePerHour: 20,
    sportCategory: 'boxing',
  },
  {
    courtId: 29,
    courtName: 'Sparring Spot',
    courtImg: '/boxing_image_5.png',
    courtDescription: 'Equipped for sparring and practice matches.',
    ownerName: 'Quinn Davis',
    ownerInitials: 'QD',
    ownerNumber: '312-555-4725',
    workingHours: '9:00 to 22:00',
    weekendHours: '9:00 to 20:00',
    pricePerHour: 16,
    sportCategory: 'boxing',
  },
  {
    courtId: 30,
    courtName: 'Uppercut Gymnasium',
    courtImg: '/boxing_image_6.png',
    courtDescription: 'Compact gym with focus on core boxing skills.',
    ownerName: 'Ray Black',
    ownerInitials: 'RB',
    ownerNumber: '312-555-0192',
    workingHours: '7:00 to 20:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 12,
    sportCategory: 'boxing',
  },
  {
    courtId: 31,
    courtName: 'Fairway Greens',
    courtImg: '/golf_image_1.png',
    courtDescription: 'Expansive course with beautiful landscapes.',
    ownerName: 'Sam Houston',
    ownerInitials: 'SH',
    ownerNumber: '312-555-1201',
    workingHours: '6:00 to 20:00',
    weekendHours: '6:00 to 20:00',
    pricePerHour: 25,
    sportCategory: 'golf',
  },
  {
    courtId: 32,
    courtName: "Eagle's Nest Club",
    courtImg: '/golf_image_2.png',
    courtDescription: 'Challenging course with expert-level holes.',
    ownerName: 'Tracy Hill',
    ownerInitials: 'TH',
    ownerNumber: '312-555-1255',
    workingHours: '7:00 to 21:00',
    weekendHours: '7:00 to 21:00',
    pricePerHour: 30,
    sportCategory: 'golf',
  },
  {
    courtId: 33,
    courtName: 'The Links Retreat',
    courtImg: '/golf_image_3.png',
    courtDescription: 'Calm and private course for focused practice.',
    ownerName: 'Victor Lane',
    ownerInitials: 'VL',
    ownerNumber: '312-555-6781',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 22:00',
    pricePerHour: 28,
    sportCategory: 'golf',
  },
  {
    courtId: 34,
    courtName: 'Golden Club Grounds',
    courtImg: '/golf_image_4.png',
    courtDescription: 'A prestigious golf course with historic value.',
    ownerName: 'Wendy Baker',
    ownerInitials: 'WB',
    ownerNumber: '312-555-4320',
    workingHours: '6:00 to 20:00',
    weekendHours: '6:00 to 18:00',
    pricePerHour: 35,
    sportCategory: 'golf',
  },
  {
    courtId: 35,
    courtName: "Champion's Fairway",
    courtImg: '/golf_image_5.png',
    courtDescription: 'Popular course for local and regional events.',
    ownerName: 'Xavier Green',
    ownerInitials: 'XG',
    ownerNumber: '312-555-5430',
    workingHours: '7:00 to 20:00',
    weekendHours: '7:00 to 19:00',
    pricePerHour: 32,
    sportCategory: 'golf',
  },
  {
    courtId: 36,
    courtName: 'The Greenspace Arena',
    courtImg: '/golf_image_6.png',
    courtDescription: 'Eco-friendly course with a unique layout.',
    ownerName: 'Yvonne Parks',
    ownerInitials: 'YP',
    ownerNumber: '312-555-8764',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 18:00',
    pricePerHour: 22,
    sportCategory: 'golf',
  },
  {
    courtId: 37,
    courtName: 'The Squash Hub',
    courtImg: '/squash_image_1.png',
    courtDescription: 'High-standard squash court with glass walls.',
    ownerName: 'Zach White',
    ownerInitials: 'ZW',
    ownerNumber: '312-555-9801',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 15,
    sportCategory: 'squash',
  },
  {
    courtId: 38,
    courtName: 'Power Play Arena',
    courtImg: '/squash_image_2.png',
    courtDescription: 'Indoor facility ideal for competitive matches.',
    ownerName: 'Anne Roberts',
    ownerInitials: 'AR',
    ownerNumber: '312-555-3452',
    workingHours: '6:00 to 21:00',
    weekendHours: '6:00 to 21:00',
    pricePerHour: 18,
    sportCategory: 'squash',
  },
  {
    courtId: 39,
    courtName: 'Speed Court',
    courtImg: '/squash_image_3.png',
    courtDescription: 'Advanced design with premium flooring.',
    ownerName: 'Bob Knight',
    ownerInitials: 'BK',
    ownerNumber: '312-555-6523',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 22:00',
    pricePerHour: 20,
    sportCategory: 'squash',
  },
  {
    courtId: 40,
    courtName: 'The Racquet Place',
    courtImg: '/squash_image_4.png',
    courtDescription: 'Focused on both beginners and advanced players.',
    ownerName: 'Cathy Mills',
    ownerInitials: 'CM',
    ownerNumber: '312-555-2324',
    workingHours: '7:00 to 21:00',
    weekendHours: '7:00 to 19:00',
    pricePerHour: 12,
    sportCategory: 'squash',
  },
  {
    courtId: 41,
    courtName: 'Victory Squash Hall',
    courtImg: '/squash_image_5.png',
    courtDescription: 'Historic court known for its championships.',
    ownerName: 'Dave Peters',
    ownerInitials: 'DP',
    ownerNumber: '312-555-9810',
    workingHours: '9:00 to 21:00',
    weekendHours: '9:00 to 21:00',
    pricePerHour: 25,
    sportCategory: 'squash',
  },
  {
    courtId: 42,
    courtName: 'Spin & Smash Court',
    courtImg: '/squash_image_6.png',
    courtDescription: 'Modern facility with top-notch amenities.',
    ownerName: 'Elise Moore',
    ownerInitials: 'EM',
    ownerNumber: '312-555-7610',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 16,
    sportCategory: 'squash',
  },
  {
    courtId: 43,
    courtName: 'Serenity Yoga Studio',
    courtImg: '/yoga_image_1.png',
    courtDescription: 'Peaceful space designed for relaxation and focus.',
    ownerName: 'Fiona Wells',
    ownerInitials: 'FW',
    ownerNumber: '312-555-2221',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 12,
    sportCategory: 'yoga',
  },
  {
    courtId: 44,
    courtName: 'Lotus Wellness Center',
    courtImg: '/yoga_image_2.png',
    courtDescription: 'Spacious and calming environment with greenery.',
    ownerName: 'Greg Stone',
    ownerInitials: 'GS',
    ownerNumber: '312-555-8742',
    workingHours: '6:00 to 21:00',
    weekendHours: '6:00 to 21:00',
    pricePerHour: 15,
    sportCategory: 'yoga',
  },
  {
    courtId: 45,
    courtName: 'Tranquil Flow Studio',
    courtImg: '/yoga_image_3.png',
    courtDescription: 'Boutique yoga studio with soft lighting.',
    ownerName: 'Holly Grant',
    ownerInitials: 'HG',
    ownerNumber: '312-555-5673',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 10,
    sportCategory: 'yoga',
  },
  {
    courtId: 46,
    courtName: 'Zen Horizon Center',
    courtImg: '/yoga_image_4.png',
    courtDescription: 'Combines yoga and meditation for mindfulness.',
    ownerName: 'Ian Forbes',
    ownerInitials: 'IF',
    ownerNumber: '312-555-9982',
    workingHours: '7:00 to 23:00',
    weekendHours: '7:00 to 23:00',
    pricePerHour: 18,
    sportCategory: 'yoga',
  },
  {
    courtId: 47,
    courtName: 'Pure Harmony Studio',
    courtImg: '/yoga_image_5.png',
    courtDescription: 'Intimate space with experienced instructors.',
    ownerName: 'Jackie Bright',
    ownerInitials: 'JB',
    ownerNumber: '312-555-2312',
    workingHours: '9:00 to 21:00',
    weekendHours: '9:00 to 21:00',
    pricePerHour: 14,
    sportCategory: 'yoga',
  },
  {
    courtId: 48,
    courtName: 'The Serenity Space',
    courtImg: '/yoga_image_6.png',
    courtDescription: 'Offers classes for all levels in a warm setting.',
    ownerName: 'Karen Diaz',
    ownerInitials: 'KD',
    ownerNumber: '312-555-4443',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 11,
    sportCategory: 'yoga',
  },
  {
    courtId: 49,
    courtName: 'FlexCore Pilates',
    courtImg: '/pilates_image_1.png',
    courtDescription: 'Modern pilates studio with expert instructors.',
    ownerName: 'Luke Powers',
    ownerInitials: 'LP',
    ownerNumber: '312-555-6732',
    workingHours: '7:00 to 22:00',
    weekendHours: '7:00 to 20:00',
    pricePerHour: 18,
    sportCategory: 'pilates',
  },
  {
    courtId: 50,
    courtName: 'Align Pilates Center',
    courtImg: '/pilates_image_2.png',
    courtDescription: 'High-quality equipment and personalized sessions.',
    ownerName: 'Mia Rivers',
    ownerInitials: 'MR',
    ownerNumber: '312-555-2376',
    workingHours: '6:00 to 21:00',
    weekendHours: '6:00 to 21:00',
    pricePerHour: 20,
    sportCategory: 'pilates',
  },
  {
    courtId: 51,
    courtName: 'The Balance Studio',
    courtImg: '/pilates_image_3.png',
    courtDescription: 'Bright and open space for peaceful workouts.',
    ownerName: 'Noah Shields',
    ownerInitials: 'NS',
    ownerNumber: '312-555-9983',
    workingHours: '8:00 to 22:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 15,
    sportCategory: 'pilates',
  },
  {
    courtId: 52,
    courtName: 'Precision Pilates Hub',
    courtImg: '/pilates_image_4.png',
    courtDescription: 'Offers reformer and mat pilates classes.',
    ownerName: 'Olivia Hill',
    ownerInitials: 'OH',
    ownerNumber: '312-555-3198',
    workingHours: '7:00 to 23:00',
    weekendHours: '7:00 to 23:00',
    pricePerHour: 22,
    sportCategory: 'pilates',
  },
  {
    courtId: 53,
    courtName: 'Core Focus Studio',
    courtImg: '/pilates_image_5.png',
    courtDescription: 'Combines pilates with core strength training.',
    ownerName: 'Paul Adams',
    ownerInitials: 'PA',
    ownerNumber: '312-555-5647',
    workingHours: '9:00 to 21:00',
    weekendHours: '9:00 to 21:00',
    pricePerHour: 17,
    sportCategory: 'pilates',
  },
  {
    courtId: 54,
    courtName: 'Reform and Restore',
    courtImg: '/pilates_image_6.png',
    courtDescription: 'Intimate studio perfect for beginners and pros.',
    ownerName: 'Quinn Foster',
    ownerInitials: 'QF',
    ownerNumber: '312-555-8762',
    workingHours: '8:00 to 20:00',
    weekendHours: '8:00 to 20:00',
    pricePerHour: 13,
    sportCategory: 'pilates',
  },
];

export async function up(sql: Sql) {
  for (const court of courts) {
    await sql`
      INSERT INTO
        courts (
          court_name,
          court_img,
          court_description,
          owner_name,
          owner_initials,
          owner_number,
          working_hours,
          weekend_hours,
          price_per_hour,
          sport_category
        )
      VALUES
        (
          ${court.courtName},
          ${court.courtImg},
          ${court.courtDescription},
          ${court.ownerName},
          ${court.ownerInitials},
          ${court.ownerNumber},
          ${court.workingHours},
          ${court.weekendHours},
          ${court.pricePerHour},
          ${court.sportCategory}
        )
    `;
  }
}

export async function down(sql: Sql) {
  for (const court of courts) {
    await sql`
      DELETE FROM courts
      WHERE
        court_id = ${court.courtId}
    `;
  }
}
