import './globals.css';
import { cookies } from 'next/headers';
import Image from 'next/image';
import LogoutButton from './(auth)/logout/LogoutButton';
import { getUser } from './database/users';
import HamburgerMenu from './HamburgerMenu';

export const metadata = {
  title: {
    default: 'Home | ArenaBook',
    template: '%s | ArenaBook',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  // 1. Checking if the sessionToken cookie exists
  const sessionTokenCookie = (await cookies()).get('sessionToken');

  // 2. Get the current logged in user from the database using the sessionToken value
  const user = sessionTokenCookie && (await getUser(sessionTokenCookie.value));

  return (
    <html lang="en">
      <body
        style={{
          background: 'url(/background-picture.png)',
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        }}
      >
        <header
          style={{
            width: '100%',
            height: '100px',
            background: 'transparent',
          }}
        >
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            <Image
              src="f7_sportscourt-fill.svg"
              alt="arena-book-logo"
              width={42}
              height={42}
            />
            <h1>ArenaBook</h1>
          </div>
          {user ? (
            <>
              <LogoutButton />
              <HamburgerMenu user={user} />
            </>
          ) : (
            <>
              <HamburgerMenu user={user} />
            </>
          )}
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
